### PR TITLE
Made version comparation a bit more elegant

### PR DESCRIPTION
**Pull request by hryamzik**

### CODE REVIEW

**Comment by angstwad** [comment]
Hi,
Thanks for helping.  Unfortunately, this PR appears incorrect.

`ansible_distribution_version | version_compare(12.04, '<')`

This line should be:
```
"(ansible_distribution_version | version_compare('12.04', '>=')) and 
 (ansible_distribution_version | version_compare('12.10', '!='))"
```

**Comment by hryamzik** [comment]
```>=``` will work on 12.04+. ```!=``` should fail on 12.04 only, doesn't seem to be a valid replacement for the original condition.

**Comment by angstwad** [comment]
Oops.  I was wrong.  :(

I think what we want is this.  We want to fail when the version is less than 12.04 or is equal to 12.10.
```
"(ansible_distribution_version | version_compare('12.04', '<')) or 
 (ansible_distribution_version | version_compare('12.10', '!='))"
```

**Comment by hryamzik** [comment]
@angstwad I've added condition to fail on 12.10, it looks a bit different than you've suggested. ;-)

**Comment by palfrey** [comment]
This breaks with 14.04. See https://gist.github.com/palfrey/8eb4440a548f322011a6 (~/src/docker.ubuntu is a checkout of current master)

**Comment by angstwad** [comment]
This is passing for me when running the Vagrant tests.  Here's a snippet of the output:

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
<127.0.0.1> REMOTE_MODULE setup
ok: [ubuntu-1404]

TASK: [docker.ubuntu | Fail if not a new release of Ubuntu] *******************
skipping: [ubuntu-1404]
```

**Comment by palfrey** [comment]
Could this be a versioning problem? Running ansible 1.5.4 (version in Ubuntu 14.04)

**Comment by angstwad** [comment]
Yes.  I believe the `version_compare` filter is added in Ansible 1.6.

**Pull request merged**
