### PR TITLE
Vagrant based test

### PR DESCRIPTION
**Pull request by mphre**
Add support for testing the role against Ubuntu LTS releases using Vagrant.

### CODE REVIEW

**Comment by angstwad** [comment]
Thanks for your three PRs!

I'm not a vagrant guy, so I don't know whether these Vagrant files work or not.  What I'm going to do is test it, since I can't just view it and visually validate that it'll work, and I'll merge when I've verified that it works.

**Comment by mphre** [comment]
cool, thanks :-)

**Comment by devvyn** [comment]
Nice work! For what it's worth, I tried it and it worked as intended. I like it! (It also helped me isolate an issue I was having in production.)

+1

**Comment by angstwad** [comment]
Thanks for your vote of confidence.  Since I'm not good with Vagrant and I haven't gotten around to it, with your note I'll merge this.

**Pull request merged**
