### PR TITLE
removed python-pip because of out-of-date request pkg

### PR DESCRIPTION
**Pull request by tomeara**
I was encountering this error:
```
:stderr: Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
```
...after some research it sounds like the requests module referenced by python-pip is either out of date, or buggy.
https://github.com/docker/docker-py/issues/525

I'm now installing python-setuptools and upgrading pip through easy_install. This has fixed my problem.

### CODE REVIEW

**Comment by angstwad** [comment]
Pretty weird bug in Ubuntu.  I don't want you to shell out to resolve this issue -- I want to use the pip module to upgrade pip.  I'll create a new branch for you to test with.

**Comment by tomeara** [comment]
:+1:

**Comment by angstwad** [comment]
Okay, so branch created called `issue35` and you can see it at f4d9ed1.

I didn't test this because I can't repeat it.  This might not work, we might need to make a separate step to make this happen.  But I *think* that the pip module when using `with_items` issues a pip command on each loop (unlike `yum` and `apt` modules), installing a single package at a time.  So if I upgrade pip with pip first, install setuptools, and then install docker-py, it should be using the latest pip and setuptools to install the docker-py package.

anyway.  give this a try.

**Comment by tomeara** [comment]
Ok, just tried that out, and works just fine for me. Thanks for the cleanup!

**Comment by angstwad** [comment]
Thanks for your help.

**Pull request closed without merging**
